### ISSUE TITLE
Initial test

### ISSUE THREAD

**Issue by Yongyao** [mudrod/xsd2owl#1]
Having followed the instructions on the readme page, I got the error message below,

```
Yongyaos-MBP:target yjiang$ java -jar xsd2owl-0.0.1-SNAPSHOT-jar-with-dependencies.jar /Users/yjiang/Documents/workspace/xsd2owl/src/main/resources/dif_v10.2.xsd 
Exception in thread "main" java.lang.NullPointerException
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:342)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.includeSchema(NGCCRuntimeEx.java:249)
	at com.sun.xml.xsom.impl.parser.state.includeDecl.action0(includeDecl.java:82)
	at com.sun.xml.xsom.impl.parser.state.includeDecl.leaveElement(includeDecl.java:149)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:314)
```

**Comment by lewismc** [comment]
OK @Yongyao 
You need to pass in the ```--inputFile``` parameter when passing in a file on the command line
Can you try again.

**Comment by Yongyao** [comment]
Sorry, I forgot that. I got a different error after adding it.

```
Yongyaos-MBP:target yjiang$ java -jar xsd2owl-0.0.1-SNAPSHOT-jar-with-dependencies.jar -inputFile /Users/yjiang/Documents/workspace/xsd2owl/src/main/resources/dif_v10.2.xsd 
22:15:28.981 [main] ERROR tr.com.srdc.ontmalizer.XSD2OWLMapper - null
22:15:29.033 [main] DEBUG Jena - Jena initialization
22:15:29.235 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorFile
22:15:29.235 [main] DEBUG org.apache.jena.util.FileManager - Add location: ClassLoaderLocator
22:15:29.236 [main] DEBUG org.apache.jena.util.LocationMapper - Failed to find configuration: file:location-mapping.rdf;file:location-mapping.n3;file:location-mapping.ttl;file:etc/location-mapping.rdf;file:etc/location-mapping.n3;file:etc/location-mapping.ttl
22:15:29.236 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorFile
22:15:29.237 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorURL
22:15:29.237 [main] DEBUG org.apache.jena.util.FileManager - Add location: ClassLoaderLocator
22:15:29.240 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorFile
22:15:29.241 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorURL
22:15:29.241 [main] DEBUG org.apache.jena.util.FileManager - Add location: ClassLoaderLocator
22:15:29.241 [main] DEBUG org.apache.jena.util.FileManager - Found: ont-policy.rdf (ClassLoaderLocator)
22:15:29.281 [main] WARN org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - unknown-source: {W136} Relative URIs are not permitted in RDF: specifically <ont-policy.rdf>
Exception in thread "main" java.lang.NullPointerException
	at tr.com.srdc.ontmalizer.XSD2OWLMapper.initOntology(XSD2OWLMapper.java:167)
	at tr.com.srdc.ontmalizer.XSD2OWLMapper.<init>(XSD2OWLMapper.java:107)
	at gov.nasa.jpl.mudrod.xsd2owl.Mapper.executeMapping(Mapper.java:56)
	at gov.nasa.jpl.mudrod.xsd2owl.Mapper.main(Mapper.java:106)
```

**Comment by lewismc** [comment]
OK thank you @Yongyao lets try and debug this and see where we get.
This issue is described at https://github.com/srdc/ontmalizer/issues/14

**Comment by lewismc** [comment]
@Yongyao did ou manage to debug this further?
If not then I will try today again. Please let me know as we need to make progress here.
